- name: Create Remote Connections on One Storage
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars:
    local_storage_serial_number: "{{ lookup('env', 'local_storage_serial_number') }}"
    remote_storage_serial_number: "{{ lookup('env', 'remote_storage_serial_number') }}"
    local_storage_address: "{{ lookup('env', 'local_storage_address') }}"
    remote_storage_address: "{{ lookup('env', 'remote_storage_address') }}"

    local_port_ctla_01: "{{ lookup('env', 'local_port_ctla_01') }}"
    remote_port_ctla_01: "{{ lookup('env', 'remote_port_ctla_01') }}"
    local_port_ctlb_01: "{{ lookup('env', 'local_port_ctlb_01') }}"
    remote_port_ctlb_01: "{{ lookup('env', 'remote_port_ctlb_01') }}"
    
    path_group_id: "{{ lookup('env', 'path_group_id') }}"
    
    connection_info:
      address: "{{ local_storage_address }}"
      username: "{{ lookup('env', 'storage_username') }}"
      password: "{{ lookup('env', 'storage_secret') }}"
      
    secondary_connection_info:
      address: "{{ remote_storage_address }}"
      username: "{{ lookup('env', 'storage_username') }}"
      password: "{{ lookup('env', 'storage_secret') }}"
    
  tasks:
    - name: Register Remote Storage
      hitachivantara.vspone_block.vsp.hv_remote_storage_registration:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        state: present
        spec:
          is_mutual_discovery: true

    - name: Create Remote Connection on a single Storage array. Do this on both sides
      hitachivantara.vspone_block.vsp.hv_remote_connection:
        connection_info: "{{ connection_info }}"
        state: present
        spec:
          path_group_id: '{{ path_group_id }}'
          remote_storage_serial_number: '{{ remote_storage_serial_number }}'
          remote_paths:
            - local_port: '{{ local_port_ctla_01 }}'
              remote_port: '{{ remote_port_ctla_01 }}'
            - local_port: '{{ local_port_ctlb_01 }}'
              remote_port: '{{ remote_port_ctlb_01 }}'
          min_remote_paths: 1
          remote_io_timeout_in_sec: 15
          round_trip_in_msec: 1
      register: result_create_remote_connection

    - name: Create Remote Connection on a secondary Storage array. 
      hitachivantara.vspone_block.vsp.hv_remote_connection:
        connection_info: "{{ secondary_connection_info }}"
        state: present
        spec:
          path_group_id: '{{ path_group_id }}'
          remote_storage_serial_number: '{{ local_storage_serial_number }}'
          remote_paths:
            - local_port: '{{ local_port_ctla_01 }}'
              remote_port: '{{ remote_port_ctla_01 }}'
            - local_port: '{{ local_port_ctlb_01 }}'
              remote_port: '{{ remote_port_ctlb_01 }}'
          min_remote_paths: 1
          remote_io_timeout_in_sec: 15
          round_trip_in_msec: 1
      register: result_create_remote_connection
    - debug:
        var: result_create_remote_connection